# Dataset configuration for Hugging Face viewer
configs:
- config_name: default
  data_files:
  - split: train
    path: "*.parquet"
  - split: recent  
    path: "recent/*.parquet"
  - split: federal
    path: "federal/*.parquet"

# Viewer settings
viewer:
  max_size_bytes: 100_000_000  # 100MB limit
  max_rows_per_split: 100_000  # 100K rows limit
  
# Dataset card settings  
dataset_info:
  description: "Political Text Scaling Dataset - Congressional speeches with pre-computed topic weights for ideology scaling research"
  citation: "Political Text Scaling Dataset: Congressional Speeches with Topic Weights, 2024"
  homepage: "https://huggingface.co/datasets/mliliu/political-text-scaling"
  license: "other"
  features:
    doc.id:
      dtype: string
      description: "Unique document identifier"
    text:
      dtype: string  
      description: "Raw speech text"
    stemmed.text:
      dtype: string
      description: "Preprocessed stemmed version of the text"
    date:
      dtype: string
      description: "Date of speech (YYYY-MM-DD)"
    congno:
      dtype: int64
      description: "Congress number (e.g., 108 = 108th Congress)"
    legis.body:
      dtype: string
      description: "Legislative body (US Senate, US House)"
    bonica.rid:
      dtype: string
      description: "Legislator (Bonica) identifier"
    training.set:
      dtype: int64
      description: "Binary indicator (1 = training, 0 = test)"