# Dataset configuration for Hugging Face viewer
configs:
- config_name: default
  data_files:
  - split: train
    path: "*.parquet"
  - split: recent  
    path: "recent/*.parquet"
  - split: federal
    path: "federal/*.parquet"

# Viewer settings
viewer:
  max_size_bytes: 100_000_000  # 100MB limit
  max_rows_per_split: 100_000  # 100K rows limit
  
# Dataset card settings  
dataset_info:
  description: "Database on Ideology, Money in Politics, and Elections (DIME) - Recipients with Campaign Finance ideology scores"
  citation: "Bonica, Adam. 2014. Mapping the ideological marketplace. American Journal of Political Science 58(2): 367-386."
  homepage: "https://data.stanford.edu/dime"
  license: "other"
  features:
    bonica.rid:
      dtype: string
      description: "Unique recipient identifier"
    name:
      dtype: string  
      description: "Recipient name"
    party:
      dtype: string
      description: "Party code (100=Dem, 200=Rep, etc.)"
    state:
      dtype: string
      description: "State abbreviation"
    cycle:
      dtype: int64
      description: "Election cycle year"
    recipient.cfscore:
      dtype: float64
      description: "Campaign Finance ideology score (-2=liberal, +2=conservative)"
    nimsp.office:
      dtype: string
      description: "Office sought (house, senate, etc.)"